#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : numatop
Version  : 2.2
Release  : 13
URL      : https://github.com/intel/numatop/archive/v2.2/numatop-2.2.tar.gz
Source0  : https://github.com/intel/numatop/archive/v2.2/numatop-2.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: numatop-bin = %{version}-%{release}
Requires: numatop-license = %{version}-%{release}
Requires: numatop-man = %{version}-%{release}
BuildRequires : numactl-dev
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(ncursesw)

%description
## Building & Installing NumaTOP
Numatop uses autotools. If you're compiling from git, run `autogen.sh`
and then `make`. Otherwise, use `./configure && make`.

%package bin
Summary: bin components for the numatop package.
Group: Binaries
Requires: numatop-license = %{version}-%{release}

%description bin
bin components for the numatop package.


%package license
Summary: license components for the numatop package.
Group: Default

%description license
license components for the numatop package.


%package man
Summary: man components for the numatop package.
Group: Default

%description man
man components for the numatop package.


%prep
%setup -q -n numatop-2.2
cd %{_builddir}/numatop-2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1632233706
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1632233706
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/numatop
cp %{_builddir}/numatop-2.2/COPYING %{buildroot}/usr/share/package-licenses/numatop/54282366b8a5e20fe355424383e0ca808b632b29
%make_install PREFIX=/usr

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/numatop

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/numatop/54282366b8a5e20fe355424383e0ca808b632b29

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/numatop.8
